// GENERATED by `pnpm configure` from each selected variant's `registries.nav`
// declaration. Provisional in the superset repo.

import type { NavItem } from '$lib/nav';

export const navItems: NavItem[] = [];
