// GENERATED by `pnpm configure`. Provisional in the superset repo.
//
// This is where the app learns its own shape. Edit freely after configure —
// nothing regenerates it.

export const appConfig = {
	name: 'niftic-app-starter',
	title: 'Niftic App Starter',
	description: 'An unconfigured Niftic app.',
	profile: 'unconfigured',
	data: 'none',
	host: 'vercel',
	auth: 'none',
	authMode: 'client',
	storage: 'none'
} as const;

/**
 * Capability flags.
 *
 * These are for RENDERING — nav labels, `/settings` sections, the health
 * payload. They are NOT a guard for importing a module that may not exist:
 * module existence is the overlay's job, and `if (has.db)` will not make an
 * unresolvable import legal.
 *
 * Keep `as const`. Widening this to `Record<string, boolean>` destroys the
 * literal types, and with them the dead-branch elimination that lets the same
 * `.svelte` markup work across profiles.
 */
export const has = {
	db: false,
	auth: false,
	organizations: false,
	storage: false,
	email: false,
	admin: false,
	example: false
} as const;

/**
 * Annotated `boolean`, NOT inferred as a literal, on purpose. `appConfig.profile`
 * is a literal type, so comparing it against 'unconfigured' in a configured app
 * is a type error rather than a false branch — TypeScript is right that the two
 * can never overlap. A widened boolean is the honest way to ask this question.
 */
export const isConfigured: boolean = false;

export type AppConfig = typeof appConfig;
export type Capability = keyof typeof has;
