// GENERATED by `pnpm configure` from each selected variant's `registries.health`
// declaration. Provisional in the superset repo.

import type { HealthCheck } from '$lib/server/health';

export const checks: HealthCheck[] = [];
