// GENERATED by `pnpm configure` from each selected variant's `registries.hooks`
// declaration. The copy in the superset repo is provisional so base typechecks
// and builds; configure overwrites it with the real sequence.
//
// Why a registry instead of variants overwriting `src/hooks.server.ts`: `handle`
// is where every cross-cutting concern lands — auth, org context, request id.
// If variants owned the file, `auth-better` + `orgs` would need a combined
// version of it, and that combinatorial explosion is the thing this avoids.

import type { Handle } from '@sveltejs/kit';
import { handleRequestId } from '$lib/server/request-id';

export const handles: Handle[] = [handleRequestId];
