/**
 * GENERATED by `pnpm types:gen`, and committed.
 *
 * Committed rather than generated at build time so a checkout typechecks
 * without a running database, and so a schema change that nobody regenerated
 * types for shows up as a diff in review. CI regenerates and fails on any
 * difference — types that have drifted from the schema are worse than no types,
 * because they are confidently wrong.
 *
 * Regenerate after every migration:
 *
 *   pnpm db:start && pnpm types:gen     # against the local stack
 *   pnpm types:gen:linked               # against the deployed project
 *
 * What follows is the shape the committed migrations produce. Replace it
 * wholesale with the generator's output — do not hand-edit it to match a schema
 * change, because the next regeneration will silently disagree with you.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
	public: {
		Tables: {
			profiles: {
				Row: {
					user_id: string;
					email: string;
					display_name: string | null;
					role: string;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					user_id: string;
					email: string;
					display_name?: string | null;
					role?: string;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					user_id?: string;
					email?: string;
					display_name?: string | null;
					role?: string;
					created_at?: string;
					updated_at?: string;
				};
				Relationships: [];
			};
			notes: {
				Row: {
					id: string;
					user_id: string;
					title: string;
					body: string;
					attachment_key: string | null;
					created_at: string;
					updated_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					title: string;
					body?: string;
					attachment_key?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					title?: string;
					body?: string;
					attachment_key?: string | null;
					created_at?: string;
					updated_at?: string;
				};
				Relationships: [];
			};
			uploads: {
				Row: {
					id: string;
					user_id: string;
					key: string;
					filename: string;
					content_type: string;
					size: number;
					created_at: string;
				};
				Insert: {
					id?: string;
					user_id: string;
					key: string;
					filename: string;
					content_type: string;
					size: number;
					created_at?: string;
				};
				Update: {
					id?: string;
					user_id?: string;
					key?: string;
					filename?: string;
					content_type?: string;
					size?: number;
					created_at?: string;
				};
				Relationships: [];
			};
			audit_log: {
				Row: {
					id: string;
					actor_id: string;
					actor_email: string;
					action: string;
					target_type: string | null;
					target_id: string | null;
					detail: Json | null;
					created_at: string;
				};
				Insert: {
					id?: string;
					actor_id: string;
					actor_email: string;
					action: string;
					target_type?: string | null;
					target_id?: string | null;
					detail?: Json | null;
					created_at?: string;
				};
				Update: never;
				Relationships: [];
			};
		};
		Views: Record<never, never>;
		Functions: Record<never, never>;
		Enums: Record<never, never>;
		CompositeTypes: Record<never, never>;
	};
}
