// GENERATED by `pnpm configure` from the `env` declarations of the selected
// variants. Provisional in the superset repo.
//
// Two deliberate choices here, both load-bearing:
//
// 1. `$env/dynamic/private`, not `$env/static/private`. Static env inlines at
//    build time and fails the build when a var is absent — which would mean the
//    preset matrix could never run `pnpm build` without a full set of real
//    secrets. Dynamic env reads at runtime, which is also what the Docker path
//    needs (build the image once, supply env per deployment).
//
// 2. Validation is lazy and memoised. A top-level `parse()` runs during SSR
//    module initialisation, i.e. during `vite build` and prerendering, and would
//    crash for the same reason. `env()` throws on first real use instead, which
//    is the correct moment.

import { env as runtime } from '$env/dynamic/private';
import { z } from 'zod';

const schema = z.object({
	ORIGIN: z.url().optional(),
	PUBLIC_APP_NAME: z.string().optional(),
	LOG_LEVEL: z.enum(['debug', 'info', 'warn', 'error']).optional(),
	/** Deploy identifier surfaced by /api/health. Set by CI or the host. */
	GIT_SHA: z.string().optional(),
	// Email. Optional in the provisional schema so the unconfigured superset
	// typechecks; configure regenerates this file and marks them required.
	RESEND_API_KEY: z.string().optional(),
	EMAIL_FROM: z.string().optional(),
	EMAIL_REPLY_TO: z.string().optional(),
	EMAIL_DRY_RUN: z.string().optional()
});

export type Env = z.infer<typeof schema>;

let cached: Env | undefined;

export function env(): Env {
	if (cached) return cached;

	const parsed = schema.safeParse(runtime);
	if (!parsed.success) {
		const detail = parsed.error.issues
			.map((issue) => `  ${issue.path.join('.') || '(root)'}: ${issue.message}`)
			.join('\n');
		// Names only — never echo values, this can reach a log aggregator.
		throw new Error(`Invalid environment configuration:\n${detail}`);
	}

	cached = parsed.data;
	return cached;
}
